spring.datasource.url=jdbc:h2:mem:smartcampusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.sql.init.mode=never

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html